set(SOURCES
	src/PCH.h
	src/main.cpp
	src/Settings.h
	src/ReloadState.h
	src/HkCompat.h
	src/HaBCRCompat.h
	src/HaBCRCompat.cpp
	src/Hooks.h
	src/Hooks.cpp
	src/InputHandler.h
	src/InputHandler.cpp
)
